name: Build & Push Docker Image to Google Artifact Registry

on:
  push:
    branches:
      - master 

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}       
  GCR_REPO_NAME: ${{ secrets.GCR_REPO_NAME }}        
  IMAGE_NAME: icliniq-node-app

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up GCP authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker to use gcloud
        run: gcloud auth configure-docker $GCP_REGION-docker.pkg.dev --quiet

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: app/package-lock.json

      - name: Install deps
        working-directory: app
        run: npm ci

      - name: Lint
        working-directory: app
        run: npm run lint

      - name: Unit tests
        working-directory: app
        run: npm test

      - name: SAST (npm audit)
        working-directory: app
        run: npm run audit

      - name: Build Docker image
        run: |
          docker build \
            -t $GCP_REGION-docker.pkg.dev/$PROJECT_ID/$GCR_REPO_NAME/$IMAGE_NAME:${{ github.sha }} ./app

      - name: Generate Trivy HTML Report
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GCR_REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          format: 'template'
          template: '@/contrib/html.tpl'
          output: 'trivy-report.html'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-security-report
          path: trivy-report.html

      - name: Push Docker image
        if: success()
        run: |
          docker push $GCP_REGION-docker.pkg.dev/$PROJECT_ID/$GCR_REPO_NAME/$IMAGE_NAME:${{ github.sha }}

      - name: Push latest tag
        if: success()
        run: |
          docker tag $GCP_REGION-docker.pkg.dev/$PROJECT_ID/$GCR_REPO_NAME/$IMAGE_NAME:${{ github.sha }} \
                     $GCP_REGION-docker.pkg.dev/$PROJECT_ID/$GCR_REPO_NAME/$IMAGE_NAME:latest
          docker push $GCP_REGION-docker.pkg.dev/$PROJECT_ID/$GCR_REPO_NAME/$IMAGE_NAME:latest
