name: Build & Push Docker Image to Google Artifact Registry

on:
  push:
    branches:
      - master 

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}       
  GCR_REPO_NAME: ${{ secrets.GCR_REPO_NAME }}        
  IMAGE_NAME: icliniq-node-app

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up GCP authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker to use gcloud
        run: gcloud auth configure-docker $GCP_REGION-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          docker build \
            -t $GCP_REGION-docker.pkg.dev/$PROJECT_ID/$GCR_REPO_NAME/$IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push $GCP_REGION-docker.pkg.dev/$PROJECT_ID/$GCR_REPO_NAME/$IMAGE_NAME:${{ github.sha }}

      - name: Push latest tag
        run: |
          docker tag $GCP_REGION-docker.pkg.dev/$PROJECT_ID/$GCR_REPO_NAME/$IMAGE_NAME:${{ github.sha }} \
                     $GCP_REGION-docker.pkg.dev/$PROJECT_ID/$GCR_REPO_NAME/$IMAGE_NAME:latest
          docker push $GCP_REGION-docker.pkg.dev/$PROJECT_ID/$GCR_REPO_NAME/$IMAGE_NAME:latest
